### ISSUE TITLE
Unexpected token in recorderWorker

### ISSUE THREAD

**Issue by MBThaumatec** [maxenceC/meteor-audio-recorder#1]
`recorderWorker.js:1     Uncaught SyntaxError: Unexpected token <`

I see this error in both Firefox and Chrome. It is JavaScript file but the content seems to be HTML. . .

**Comment by maxenceC** [comment]
You are correct, the  specified path of the recorder worker isn't correct, I'll fix that asap

**Comment by ecwyne** [comment]
Fix proposed in #2

**Comment by maxenceC** [comment]
@ecwyne thanks, I just merged your fix
